### ISSUE TITLE
Failed to install warbler with gem from remote

### ISSUE THREAD

**Issue by foxban** [jruby/warbler#207]
While installing directly:

gem install -V warbler
HEAD http://ruby.taobao.org/latest_specs.4.8.gz
200 OK
GET http://ruby.taobao.org/latest_specs.4.8.gz
200 OK
ERROR:  While executing gem ... (Java::JavaLang::NullPointerException)

While installing with bundler:

 bundle install
Fetching source index from http://ruby.taobao.org/
Unfortunately, a fatal error has occurred. Please see the Bundler
troubleshooting documentation at http://bit.ly/bundler-issues. Thanks!
MultiByteEncoding.java:45:in `length': java.lang.NullPointerException
	from StringSupport.java:568:in `bytesToFixBrokenTrailingCharacter'
	from JZlibRubyGzipReader.java:701:in `fixBrokenTrailingCharacter'
	from JZlibRubyGzipReader.java:425:in `readAll'
	from JZlibRubyGzipReader.java:409:in `readAll'
	from JZlibRubyGzipReader.java:331:in `read'
	from JZlibRubyGzipReader$INVOKER$i$0$1$read.gen:-1:in `call'
	from JavaMethod.java:661:in `call'
	from DynamicMethod.java:198:in `call'
	from CachingCallSite.java:306:in `cacheAndCall'
	from CachingCallSite.java:136:in `call'
	from CallNoArgNode.java:60:in `interpret'
	from LocalAsgnNode.java:123:in `interpret'
	from NewlineNode.java:105:in `interpret'
	from BlockNode.java:71:in `interpret'
	from ASTInterpreter.java:74:in `INTERPRET_METHOD'
	from InterpretedMethod.java:182:in `call'
	from DefaultMethod.java:198:in `call'
	from CachingCallSite.java:326:in `cacheAndCall'
	from CachingCallSite.java:170:in `call'

.....

cloned the git repo and built the gem locally resolved the problem..

**Comment by jkutner** [comment]
Since this is not necessarily a bug or feature request, I’m going to close the issue. If you still have questions or unresolved issues, please start a discussion on the JRuby mailing list[1] or create a question of Stackoverflow.com[2]. Most of the Warbler maintainers hang out on IRC too, so you can find us in #jruby on freenode. Thanks.

[1] https://github.com/jruby/jruby/wiki/MailingLists
[2] http://stackoverflow.com/
