### ISSUE TITLE
Another beginner question related to specifying resources to be compiled

### ISSUE THREAD

**Issue by Integralist** [jruby/warbler#233]
Hi,

I was recently pointed in the right direction regarding compiling a simple jRuby application (see https://github.com/jruby/warbler/issues/232).

I've only just had a chance to come back to this example project and realised that I've got a very similar issue but unfortunately the 'obvious' fix didn't seem to work for me.

My repo can be seen here: https://github.com/Integralist/jruby-testing

The problem I'm having is that I'm trying to load a CSS style sheet within a HTML page but when I specify that directory `"Styles/test.css"` (I originally tried `"Styles/*"` but that didn't work either) and I compiled my code `warble executable war`, then run it `java -jar mycustomname.war` and view it `http://localhost:8080/` the styles within the CSS aren't applied which means the file isn't being found and/or included in the war package.

What am I missing? Apologies for the silly question :-/

**Comment by jkutner** [comment]
Since this is not necessarily a bug or feature request, I’m going to close the issue. If you still have questions or unresolved issues, please start a discussion on the JRuby mailing list[1] or create a question of Stackoverflow.com[2]. Most of the Warbler maintainers hang out on IRC too, so you can find us in #jruby on freenode. Thanks.

[1] https://github.com/jruby/jruby/wiki/MailingLists
[2] http://stackoverflow.com/
