### ISSUE TITLE
Adding Rails Engine/Plugin to a Warbled Rails Application

### ISSUE THREAD

**Issue by zquintana** [jruby/warbler#295]
This may seem like a bit of a crazy question, but I'm wondering if it's possible to load a plugin into a rails application that has been warbled. Reason for the question is that I'm looking into alternative methods of building/distributing an extensible application. Would that sort of thing be possible if the main rails application has been warbled? If it's not, can I call in a plugin to a standard rails app a warbled rails engine?

**Comment by jkutner** [comment]
Since this is not necessarily a bug or feature request, I’m going to close the issue. If you still have questions or unresolved issues, please start a discussion on the JRuby mailing list[1] or create a question of Stackoverflow.com[2]. Most of the Warbler maintainers hang out on IRC too, so you can find us in #jruby on freenode. Thanks.

[1] https://github.com/jruby/jruby/wiki/MailingLists
[2] http://stackoverflow.com/
