### ISSUE TITLE
File/Image uploads with carrierwave or paperclip?

### ISSUE THREAD

**Issue by Allanon29** [jruby/warbler#306]
I am trying to deploy a simple CMS app which has an image/file library, and also SpreeCommerce where product image uploads are essential. Right now I get 500 error when I try to upload.
I tried to include a symlink for uploads in the public directory before I created a war file but that doesn't seem to work.

My questions is:
How can I configure carrierwave and/or paperclip to work when I deploy with a .war file? Any best practice for this? I am sure many have run into this issue.

**Comment by jkutner** [comment]
Since this is not necessarily a bug or feature request, I’m going to close the issue. If you still have questions or unresolved issues, please start a discussion on the JRuby mailing list[1] or create a question of Stackoverflow.com[2]. Most of the Warbler maintainers hang out on IRC too, so you can find us in #jruby on freenode. Thanks.

[1] https://github.com/jruby/jruby/wiki/MailingLists
[2] http://stackoverflow.com/
