### ISSUE TITLE
Gemfile not found

### ISSUE THREAD

**Issue by dfl** [jruby/warbler#371]
example code here: https://github.com/dfl/jruby_art-warbler-example

I'm getting the following error:
uri:classloader:/jruby_art-warbler-example/Gemfile not found

when I pop open the jar file, there is a Gemfile. Strangely it is marked as executable.

**Comment by jkutner** [comment]
I wasn't able to try this because I don't have the jruby_art gem. Before I go any further, can you make sure you're using JRuby 9.0.5.0? I noticed RVM thinks [jruby-9](https://github.com/dfl/jruby_art-warbler-example/blob/master/.ruby-version) means jruby-9.0.0.0.pre1

**Comment by dfl** [comment]
Yes I'm using jruby 9.0.5.0. jruby_art should install with bundler, as part of warble packaging, no? Thanks for your help!

**Comment by jkutner** [comment]
I see. not sure what happened to me (probably a network problem). I'm able to reproduce the issue now.

**Comment by kares** [comment]
this is a problem with isolation - you need to make sure no BUNDLE/GEM env variables are interfering.

running the warbled app `java -jar jruby_art-warbler-example.jar` ended up as : 
```
Errno::ENOENT: No such file or directory - bundle
  _exec_internal at org/jruby/RubyKernel.java:1635
            exec at uri:classloader:/jruby/kernel/kernel.rb:17
           <top> at uri:classloader:/jruby_art-warbler-example/bin/_run.rb:1
            load at org/jruby/RubyKernel.java:962
           <top> at uri:classloader:/META-INF/main.rb:1
         require at org/jruby/RubyKernel.java:944
          (root) at uri:classloader:/META-INF/main.rb:1
           <top> at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1
```
... which is fine since you should not expect a packed up spawn ruby bins like a standalone installation.
the idea is that a executable Ruby `bin/script` would not depend on running other gem executables ...
