### ISSUE TITLE
Set RAILS_ENV on AWS Elastic Beanstalk

### ISSUE THREAD

**Issue by HarlemSquirrel** [jruby/warbler#425]
I know [this PR](https://github.com/jruby/warbler/commit/c8ec453816ca452d2945014aaaf6f6a3e50d8e5a) was merged a while back but I'm having trouble getting this to work. 

I set `RAILS_ENV` to `staging` via the "Environment Properties" section in the web GUI but my app still runs with `RAILS_ENV` as `production`. I added an element to my footer the shows the output of `ENV['RAILS_ENV']` is `production`.

**Comment by JasonLunn** [comment]
You would think since AWS refers to them as "Environment Properties" that they mean environment variables. Or perhaps you were misled by the heading below that on the console, which helpfully explains "The following properties are passed into the application as environment variables". Lies I say. 

Per the AWS [Elastic Beanstalk documentation](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/java-tomcat-platform.html), you're expected to read them by looking up Java properties, not environment variables. They even give a helpful example:
```
String endpoint = System.getProperty("API_ENDPOINT");
```

Warbler would need to look up `RAILS_ENV` as an environment variable,  a Java property, and an element of the configuration in order for this to work.

**Comment by HarlemSquirrel** [comment]
As I suspected. Thanks for the explaination. Would this be something Warbler might accept as a PR?

**Comment by mkristian** [comment]
@JasonLunn sure any PR which makes warbled project usable by more frameworks is welcome. not sure if this can be made very generic.

**Comment by kares** [comment]
https://github.com/jruby/warbler/pull/427
